<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Event;
use Carbon\Carbon;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        
        // Upcoming events (next few days)
        $upcomingEvents = [
            [
                'title' => 'Stargate Project Infrastructure Launch',
                'description' => 'Join us for the official launch of the Stargate Project infrastructure. Learn about the $500 billion AI infrastructure initiative, its technical architecture, and how it will reshape the future of artificial intelligence.',
                'category' => 'stargate',
                'type' => 'conference',
                'event_date' => $now->copy()->addDays(3),
                'event_time' => '10:00:00',
                'location' => 'San Francisco, CA & Virtual',
                'organizer' => 'OpenAI & SoftBank',
                'icon' => '🚀',
                'registration_url' => 'https://stargate.ci/events/register',
                'source' => 'internal',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Cristal Intelligence Ethics Workshop',
                'description' => 'Deep dive into transparent AI development and ethical AI implementation. Explore how Cristal Intelligence ensures accountability, fairness, and transparency in AI systems.',
                'category' => 'cristal',
                'type' => 'workshop',
                'event_date' => $now->copy()->addDays(7),
                'event_time' => '14:00:00',
                'location' => 'London, UK & Virtual',
                'organizer' => 'Cristal Intelligence Team',
                'icon' => '💎',
                'registration_url' => 'https://stargate.ci/events/cristal-workshop',
                'source' => 'internal',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'AI Infrastructure Partnership Meeting',
                'description' => 'Strategic meeting with key partners including OpenAI, SoftBank, Arm Holdings, and Oracle to discuss the next phase of Stargate Project development.',
                'category' => 'meetings',
                'type' => 'meeting',
                'event_date' => $now->copy()->addDays(10),
                'event_time' => '09:00:00',
                'location' => 'Tokyo, Japan',
                'organizer' => 'SoftBank Group',
                'icon' => '🤝',
                'registration_url' => null,
                'source' => 'softbank',
                'is_featured' => false,
                'is_active' => true,
            ],
        ];

        // This month events
        $thisMonthEvents = [
            [
                'title' => 'Stargate Technical Deep Dive',
                'description' => 'Comprehensive technical presentation on Stargate Project architecture, including distributed computing, AI model training infrastructure, and data pipeline design.',
                'category' => 'stargate',
                'type' => 'conference',
                'event_date' => $now->copy()->addDays(15),
                'event_time' => '11:00:00',
                'location' => 'Virtual',
                'organizer' => 'OpenAI Engineering Team',
                'icon' => '🔧',
                'registration_url' => 'https://stargate.ci/events/technical-deep-dive',
                'video_url' => 'https://www.youtube.com/watch?v=GhIJs4zbH0o',
                'source' => 'openai',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Cristal Intelligence Transparency Framework',
                'description' => 'Introduction to the Cristal Intelligence transparency framework. Learn how to implement ethical AI practices in your organization.',
                'category' => 'cristal',
                'type' => 'workshop',
                'event_date' => $now->copy()->addDays(18),
                'event_time' => '15:00:00',
                'location' => 'New York, NY & Virtual',
                'organizer' => 'Cristal Intelligence',
                'icon' => '💎',
                'registration_url' => 'https://stargate.ci/events/cristal-framework',
                'source' => 'internal',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'AI Safety and Alignment Conference',
                'description' => 'Major conference on AI safety, alignment, and governance. Featuring leading researchers and policymakers discussing the future of safe AI development.',
                'category' => 'conferences',
                'type' => 'conference',
                'event_date' => $now->copy()->addDays(22),
                'event_time' => '09:00:00',
                'location' => 'Cambridge, UK',
                'organizer' => 'AI Safety Research Institute',
                'icon' => '🎤',
                'registration_url' => 'https://stargate.ci/events/ai-safety',
                'source' => 'internal',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Stargate Project Q4 Milestone Announcement',
                'description' => 'Official announcement of Q4 milestones and achievements in the Stargate Project. Updates on infrastructure deployment, partnerships, and future roadmap.',
                'category' => 'announcements',
                'type' => 'announcement',
                'event_date' => $now->copy()->addDays(25),
                'event_time' => '12:00:00',
                'location' => 'Virtual',
                'organizer' => 'Stargate Project Team',
                'icon' => '📢',
                'registration_url' => null,
                'video_url' => null,
                'source' => 'internal',
                'is_featured' => true,
                'is_active' => true,
            ],
        ];

        // Next month events
        $nextMonthEvents = [
            [
                'title' => 'Stargate Global Summit 2025',
                'description' => 'The premier event for the Stargate Project ecosystem. Join industry leaders, researchers, and innovators for three days of keynotes, workshops, and networking.',
                'category' => 'conferences',
                'type' => 'conference',
                'event_date' => $now->copy()->addMonth()->startOfMonth()->addDays(5),
                'event_time' => '08:00:00',
                'location' => 'San Francisco, CA',
                'organizer' => 'Stargate Project',
                'icon' => '🌐',
                'registration_url' => 'https://stargate.ci/events/global-summit',
                'source' => 'internal',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Cristal Intelligence Developer Workshop',
                'description' => 'Hands-on workshop for developers interested in implementing Cristal Intelligence principles in their AI projects. Includes coding sessions and best practices.',
                'category' => 'cristal',
                'type' => 'workshop',
                'event_date' => $now->copy()->addMonth()->startOfMonth()->addDays(12),
                'event_time' => '10:00:00',
                'location' => 'Virtual',
                'organizer' => 'Cristal Intelligence',
                'icon' => '👨‍💻',
                'registration_url' => 'https://stargate.ci/events/cristal-developer',
                'source' => 'internal',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Partnership Announcement: Oracle & Stargate',
                'description' => 'Major partnership announcement between Oracle and the Stargate Project. Learn about cloud infrastructure integration and collaborative initiatives.',
                'category' => 'announcements',
                'type' => 'announcement',
                'event_date' => $now->copy()->addMonth()->startOfMonth()->addDays(18),
                'event_time' => '14:00:00',
                'location' => 'Austin, TX & Virtual',
                'organizer' => 'Oracle & Stargate Project',
                'icon' => '🤝',
                'registration_url' => 'https://stargate.ci/events/oracle-partnership',
                'source' => 'oracle',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'AI Infrastructure Best Practices',
                'description' => 'Learn from industry experts about best practices for building and scaling AI infrastructure. Case studies from the Stargate Project implementation.',
                'category' => 'stargate',
                'type' => 'workshop',
                'event_date' => $now->copy()->addMonth()->startOfMonth()->addDays(24),
                'event_time' => '11:00:00',
                'location' => 'Virtual',
                'organizer' => 'Stargate Engineering',
                'icon' => '📚',
                'registration_url' => 'https://stargate.ci/events/best-practices',
                'source' => 'internal',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Cristal Intelligence Community Meetup',
                'description' => 'Monthly community meetup for Cristal Intelligence enthusiasts. Share experiences, discuss challenges, and network with like-minded professionals.',
                'category' => 'cristal',
                'type' => 'meeting',
                'event_date' => $now->copy()->addMonth()->startOfMonth()->addDays(28),
                'event_time' => '18:00:00',
                'location' => 'Multiple Cities & Virtual',
                'organizer' => 'Cristal Intelligence Community',
                'icon' => '👥',
                'registration_url' => 'https://stargate.ci/events/community-meetup',
                'source' => 'internal',
                'is_featured' => false,
                'is_active' => true,
            ],
        ];

        // Additional events for all categories
        $additionalEvents = [
            // Stargate Project Events
            [
                'title' => 'Stargate AI Infrastructure Webinar',
                'description' => 'Join us for an in-depth webinar on Stargate Project\'s AI infrastructure architecture, covering distributed computing, model training pipelines, and scalability solutions.',
                'category' => 'stargate',
                'type' => 'workshop',
                'event_date' => $now->copy()->addDays(5),
                'event_time' => '15:00:00',
                'location' => 'Virtual',
                'organizer' => 'Stargate Engineering',
                'icon' => '🚀',
                'registration_url' => 'https://stargate.ci/events/webinar',
                'source' => 'internal',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Stargate Project Roadmap 2025',
                'description' => 'Exclusive presentation of the Stargate Project roadmap for 2025, including milestones, partnerships, and technological breakthroughs.',
                'category' => 'stargate',
                'type' => 'announcement',
                'event_date' => $now->copy()->addDays(20),
                'event_time' => '11:00:00',
                'location' => 'Virtual',
                'organizer' => 'Stargate Project',
                'icon' => '🗺️',
                'registration_url' => null,
                'video_url' => null,
                'source' => 'internal',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Stargate Infrastructure Deep Dive',
                'description' => 'Technical deep dive into Stargate\'s infrastructure components, including GPU clusters, networking, and data management systems.',
                'category' => 'stargate',
                'type' => 'conference',
                'event_date' => $now->copy()->addMonth()->startOfMonth()->addDays(8),
                'event_time' => '10:00:00',
                'location' => 'San Francisco, CA',
                'organizer' => 'OpenAI & SoftBank',
                'icon' => '🔧',
                'registration_url' => 'https://stargate.ci/events/deep-dive',
                'source' => 'openai',
                'is_featured' => false,
                'is_active' => true,
            ],

            // Cristal Intelligence Events
            [
                'title' => 'Cristal Intelligence Transparency Framework Launch',
                'description' => 'Official launch of the Cristal Intelligence transparency framework. Learn how to implement ethical AI practices and ensure transparency in your AI systems.',
                'category' => 'cristal',
                'type' => 'announcement',
                'event_date' => $now->copy()->addDays(6),
                'event_time' => '13:00:00',
                'location' => 'Virtual',
                'organizer' => 'Cristal Intelligence',
                'icon' => '💎',
                'registration_url' => 'https://stargate.ci/events/cristal-launch',
                'source' => 'internal',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Ethical AI Implementation Workshop',
                'description' => 'Hands-on workshop on implementing ethical AI principles from Cristal Intelligence. Case studies and best practices for responsible AI development.',
                'category' => 'cristal',
                'type' => 'workshop',
                'event_date' => $now->copy()->addDays(14),
                'event_time' => '14:00:00',
                'location' => 'New York, NY & Virtual',
                'organizer' => 'Cristal Intelligence',
                'icon' => '⚖️',
                'registration_url' => 'https://stargate.ci/events/ethical-ai',
                'source' => 'internal',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Cristal Intelligence Research Symposium',
                'description' => 'Annual research symposium showcasing the latest advances in transparent AI, ethical AI development, and AI governance.',
                'category' => 'cristal',
                'type' => 'conference',
                'event_date' => $now->copy()->addMonth()->startOfMonth()->addDays(15),
                'event_time' => '09:00:00',
                'location' => 'Cambridge, UK',
                'organizer' => 'Cristal Intelligence Research',
                'icon' => '🎓',
                'registration_url' => 'https://stargate.ci/events/symposium',
                'source' => 'internal',
                'is_featured' => true,
                'is_active' => true,
            ],

            // Conferences
            [
                'title' => 'AI Infrastructure Summit 2025',
                'description' => 'Premier conference on AI infrastructure, featuring keynotes from industry leaders, technical sessions, and networking opportunities.',
                'category' => 'conferences',
                'type' => 'conference',
                'event_date' => $now->copy()->addDays(12),
                'event_time' => '08:00:00',
                'location' => 'Las Vegas, NV',
                'organizer' => 'AI Infrastructure Alliance',
                'icon' => '🎤',
                'registration_url' => 'https://stargate.ci/events/summit',
                'source' => 'internal',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Future of AI Conference',
                'description' => 'Explore the future of artificial intelligence with leading researchers, entrepreneurs, and policymakers. Keynotes, panels, and breakout sessions.',
                'category' => 'conferences',
                'type' => 'conference',
                'event_date' => $now->copy()->addDays(28),
                'event_time' => '09:00:00',
                'location' => 'Boston, MA',
                'organizer' => 'AI Future Foundation',
                'icon' => '🔮',
                'registration_url' => 'https://stargate.ci/events/future-ai',
                'source' => 'internal',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Machine Learning & AI Expo',
                'description' => 'Comprehensive expo showcasing the latest in machine learning and AI technologies. Exhibitions, demos, and expert presentations.',
                'category' => 'conferences',
                'type' => 'conference',
                'event_date' => $now->copy()->addMonth()->startOfMonth()->addDays(20),
                'event_time' => '10:00:00',
                'location' => 'London, UK',
                'organizer' => 'ML & AI Expo',
                'icon' => '🤖',
                'registration_url' => 'https://stargate.ci/events/ml-expo',
                'source' => 'internal',
                'is_featured' => false,
                'is_active' => true,
            ],

            // Meetings
            [
                'title' => 'Stargate Project Partner Meeting',
                'description' => 'Quarterly partner meeting to discuss progress, challenges, and strategic initiatives for the Stargate Project.',
                'category' => 'meetings',
                'type' => 'meeting',
                'event_date' => $now->copy()->addDays(8),
                'event_time' => '10:00:00',
                'location' => 'San Francisco, CA',
                'organizer' => 'Stargate Project Partners',
                'icon' => '🤝',
                'registration_url' => null,
                'source' => 'internal',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'AI Ethics Board Meeting',
                'description' => 'Monthly meeting of the AI Ethics Board to review policies, discuss ethical considerations, and provide guidance on AI development practices.',
                'category' => 'meetings',
                'type' => 'meeting',
                'event_date' => $now->copy()->addDays(16),
                'event_time' => '14:00:00',
                'location' => 'Virtual',
                'organizer' => 'AI Ethics Board',
                'icon' => '⚖️',
                'registration_url' => null,
                'source' => 'internal',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Technical Advisory Committee',
                'description' => 'Meeting of the Technical Advisory Committee to review technical proposals, architecture decisions, and provide expert guidance.',
                'category' => 'meetings',
                'type' => 'meeting',
                'event_date' => $now->copy()->addMonth()->startOfMonth()->addDays(10),
                'event_time' => '11:00:00',
                'location' => 'Virtual',
                'organizer' => 'Technical Advisory Committee',
                'icon' => '👥',
                'registration_url' => null,
                'source' => 'internal',
                'is_featured' => false,
                'is_active' => true,
            ],

            // Announcements
            [
                'title' => 'Stargate Project Phase 2 Launch',
                'description' => 'Major announcement: Launch of Stargate Project Phase 2, expanding infrastructure capabilities and introducing new AI model training facilities.',
                'category' => 'announcements',
                'type' => 'announcement',
                'event_date' => $now->copy()->addDays(9),
                'event_time' => '12:00:00',
                'location' => 'Virtual',
                'organizer' => 'Stargate Project',
                'icon' => '📢',
                'registration_url' => null,
                'video_url' => null,
                'source' => 'internal',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'New Partnership: Oracle & Stargate',
                'description' => 'Announcement of strategic partnership between Oracle and the Stargate Project, bringing cloud infrastructure expertise to the initiative.',
                'category' => 'announcements',
                'type' => 'announcement',
                'event_date' => $now->copy()->addDays(19),
                'event_time' => '15:00:00',
                'location' => 'Virtual',
                'organizer' => 'Oracle & Stargate Project',
                'icon' => '🤝',
                'registration_url' => null,
                'source' => 'oracle',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Cristal Intelligence Open Source Release',
                'description' => 'Major announcement: Cristal Intelligence framework released as open source. Access transparency tools and ethical AI guidelines.',
                'category' => 'announcements',
                'type' => 'announcement',
                'event_date' => $now->copy()->addDays(26),
                'event_time' => '10:00:00',
                'location' => 'Virtual',
                'organizer' => 'Cristal Intelligence',
                'icon' => '📦',
                'registration_url' => null,
                'source' => 'internal',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Stargate Project Investment Update',
                'description' => 'Quarterly investment update: Progress on the $500 billion Stargate Project infrastructure investment and allocation breakdown.',
                'category' => 'announcements',
                'type' => 'announcement',
                'event_date' => $now->copy()->addMonth()->startOfMonth()->addDays(3),
                'event_time' => '14:00:00',
                'location' => 'Virtual',
                'organizer' => 'Stargate Project Finance',
                'icon' => '💰',
                'registration_url' => null,
                'source' => 'internal',
                'is_featured' => false,
                'is_active' => true,
            ],
        ];

        // Combine all events
        $allEvents = array_merge($upcomingEvents, $thisMonthEvents, $nextMonthEvents, $additionalEvents);

        // Create events
        foreach ($allEvents as $eventData) {
            Event::firstOrCreate(
                [
                    'title' => $eventData['title'],
                    'event_date' => $eventData['event_date'],
                ],
                $eventData
            );
        }
    }
}

