name: Deploy to stargate.ci

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Build frontend
      run: |
        cd frontend
        npm run build
    
    - name: Create deployment package
      run: |
        cd frontend
        tar -czf ../stargate-ci-auto-deploy.tar.gz -C dist .
    
    # FTP deployment disabled - manual deployment only
    # - name: Deploy via FTP
    #   uses: SamKirkland/FTP-Deploy-Action@v4.3.4
    #   with:
    #     server: ${{ secrets.FTP_SERVER }}
    #     username: ${{ secrets.FTP_USERNAME }}
    #     password: ${{ secrets.FTP_PASSWORD }}
    #     local-dir: frontend/dist/
    #     server-dir: /public_html/
    #     exclude: |
    #       **/.git*
    #       **/.git*/**
    #       **/node_modules/**
    
    - name: Notify deployment package ready
      run: |
        echo "✅ Deployment package created successfully!"
        echo "📦 Package: stargate-ci-auto-deploy.tar.gz"
        echo "📋 Manual upload required - FTP deployment disabled"
